# Generated by Django 3.1.6 on 2021-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_postfiles_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfiles',
            name='file_name',
            field=models.CharField(default='Unnamed File', max_length=256),
        ),
    ]
